;===========================================================
; ASCII characters.
;===========================================================

;NUL		EQU	00H
SOH		EQU	01H
STX		EQU	02H
ETX		EQU	03H
EOT		EQU	04H
ENQ		EQU	05H
ACK		EQU	06H
BEL		EQU	07H
BS		EQU	08H
HT		EQU	09H
LF		EQU	0AH
VT		EQU	0BH
FF		EQU	0CH
CR		EQU	0DH
SO		EQU	0EH
SI		EQU	0FH
DLE		EQU	10H
DC1		EQU	11H
DC2		EQU	12H
DC3		EQU	13H
DC4		EQU	14H
NAK		EQU	15H
SYN		EQU	16H
ETB		EQU	17H
CAN		EQU	18H
EM		EQU	19H
SUB		EQU	1AH
ESC		EQU	1BH
FS		EQU	1CH
GS		EQU	1DH
RS		EQU	1EH
US		EQU	1FH
