M48
; DRILL file {KiCad (6.0.4)} date Mon Jun  6 18:53:06 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-06T18:53:06+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.1200
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.2362
%
G90
G05
T1
X4.825Y-2.48
X4.825Y-2.705
X4.825Y-2.88
X4.825Y-3.055
X4.825Y-4.83
T2
X4.55Y-3.405
T0
M30
