tasm -80 source\basic.asm hexFiles\basic.hex
tasm -80 source\monitor.asm hexFiles\monitor.hex
tasm -80 source\cbios64.asm hexFiles\cbios64.hex
tasm -80 source\cbios128.asm hexFiles\cbios128.hex
tasm -80 source\cpm22.asm hexFiles\cpm22.hex
tasm -80 source\form64.asm hexFiles\form64.hex
tasm -80 source\form128.asm hexFiles\form128.hex
tasm -80 source\putsys.asm hexFiles\putsys.hex
tasm -80 source\download.asm hexFiles\download.hex

pause
